### ISSUE TITLE
Publish to bintray and add to Grails Plugin Repo

### ISSUE THREAD

**Issue by ctoestreich** [rmorrise/grails-cascade-validation#11]
https://medium.com/@benorama/how-to-publish-your-grails-3-plugin-to-bintray-c341b24f567d#.35bmwld81

**Comment by rvanderwerf** [comment]
could we also have a non-snapshot version? it seems to be working well enough for us

**Comment by ctoestreich** [comment]
I am going to add from my repo for the time being to give people access to this.

**Comment by rmorrise** [comment]
Now in v3.0.0
