### ISSUE TITLE
Work out which is the official plugin

### ISSUE THREAD

**Issue by sbglasius** [rmorrise/grails-cascade-validation#15]
Seems that there are two plugins, but both somewhat out of sync. It would be great if you and @ctoestreich could work out, which one is the official. 

Thanks guys!

**Comment by ctoestreich** [comment]
My brain doesn’t even remember back a few days ago. I can’t remember exactly why I forked an updated this one. I think I may have added everyone else authors on this new consolidated repo. Seems like they are both about the same timeframe of updates. There’s a couple open Pull requests for this one that may be worth actually merging in. I’m happy to make you a plug-in owner is Soren if you want to contribute to this one

**Comment by sbglasius** [comment]
@ctoestreich I'm upgrading to Grails 3.3, thus having @virtualdogbert  PR would be nice. I can do some low-effort maintenance but not more than that. 

I also think we should see what @rmorrise thinks about the situation :smile:

**Comment by rmorrise** [comment]
@sbglasius I would be happy to have one official repo that several people share admin over.

If there is an official github org for Grails 3 plugins, I would like to transfer ownership to that org, then assign myself, @asoftwareguy, and whoever else wants to work on it as mods/contributors. I think that would be the best way forward.

What do you think?

**Comment by rmorrise** [comment]
I couldn't find @ctoestreich 's fork. It looks like maybe it was deleted?

I think the main fork is @virtualdogbert 's, which seems to be set up with bintray publishing.

**Comment by virtualdogbert** [comment]
I have a pull request there where I redid how the constraint was registered, and made some changes, to get it to work.

@sbglasius as a temp solution, because I was waiting on this, the command plugin also has a copy of the cascade constraint, along with some others, and it is set up for Grails 3.3, although you do get a little extra that comes with it.

**Comment by rmorrise** [comment]
@ctoestreich what I'd like to do, if you agree, is transfer ownership of my repo to an org and roll your changes in as a PR. I will make you a project admin, so you can set up the bintray publishing.

@sbglasius If it's OK with you, we could roll it into the official grails-plugins org. If not, maybe we can use Christian's existing org.

We'll want to also use a bintray org that we can share admin of.

Let me know what you folks want to do.

**Comment by sbglasius** [comment]
@ctoestreich @rmorrise I have asked the owners of https://github.com/grails3-plugins and https://github.com/gpc (Grails plugin collective) it it would be a good fit (in the Grails Slack group #plugins) 

IMO there are too many collections of plugins that duplicate other plugins.

**Comment by sbglasius** [comment]
@rmorrise I was just checking, and it looks as if merging from the Grails-Plugin-Consortium:master to your (as you were the origin) would be easiest, then @ctoestreich could make a PR back to Grails-Plugin-Consortium making it the "new home"?

https://github.com/rmorrise/grails-cascade-validation/compare/master...Grails-Plugin-Consortium:master

**Comment by sbglasius** [comment]
Looks like https://github.com/gpc would be a possibility. What do you think?

**Comment by rmorrise** [comment]
Working on reconciling the forks.

It looks like @ctoestreich's only change was to add bintray publishing for Grails 3.0.x.

The `grailsPublish` config from 3.1.x replaces the `bintray` config. Since I started coding the `grailsPublish` config already, I'm going to abandon the rebase and work on finishing what I already started on my master. I'll add Christian as one of the project developers.

Looking at the PRs on @ctoestreich's project...
I believe gtor's changes are already included in my repo.

I'll work on merging in @virtualdogbert 's changes after I've managed to publish a snapshot version to bintray.

**Comment by rmorrise** [comment]
@sbglasius I would be happy to move the project to GPC. How do I join that org? And is there a bintray org that I can join as well?

Thanks

**Comment by ctoestreich** [comment]
My time is spread too thin these days. Let me know what you need from me and I can move, merge or delet any repos in my github org.

**Comment by rmorrise** [comment]
Opened #19

**Comment by rmorrise** [comment]
Until I am able to get added to GPC, I will continue hosting it here.

I will publish to: https://bintray.com/cscpublicgrails/plugins
...and link it to jcenter.

**Comment by sbglasius** [comment]
The plugin is now forked to https://github.com/cpc and @rmorrise is added as owner and @ctoestreich as committer.

**Comment by rmorrise** [comment]
The official repo is now:
https://github.com/gpc/grails-cascade-validation

@ctoestreich @virtualdogbert Please re-create from the new master repo if possible. Thanks!
