### ISSUE TITLE
Constraint isn't registered in unit test environment

### ISSUE THREAD

**Issue by rmorrise** [rmorrise/grails-cascade-validation#2]
When running a unit test, the cascade constraint isn't registered with grails. To work around this issue, the following code must be added to the setup() method of the test:

```
def setup() {
        ConstrainedProperty.registerNewConstraint(CascadeValidationConstraint.NAME, CascadeValidationConstraint)
    }
```

Ideally, the plugin should automatically register itself in the test environment.

**Comment by julienCsj** [comment]
The bug is still present. I'm using version 2.0.2 with Grails 3.1.4
I've spent a lot of time to make my tests pass.
I think you must add a line in the plugin documentation.

**Comment by rmorrise** [comment]
Added to the README. Sorry for the inconvenience.

**Comment by rmorrise** [comment]
Closed to: https://github.com/gpc/grails-cascade-validation/issues/3
