### ISSUE TITLE
trailing comma in collection causes null pointer exception

### ISSUE THREAD

**Issue by hzill** [rmorrise/grails-cascade-validation#6]
A poorly formatted JSON document causes the plugin to throw a null pointer exception when validating objects in a collection. This occurs if there is a trailing comma after the last object in the collection. Grails will pass a list containing the objects in the list plus a null object. The plugin does not handle this null object gracefully.

**Comment by rmorrise** [comment]
Thanks for reporting this issue! I will make sure it gets added to my team's backlog.

**Comment by rmorrise** [comment]
Migrated issue to the new GPC repo:
https://github.com/gpc/grails-cascade-validation/issues/2
