### ISSUE TITLE
Errors are added for every validate() call

### ISSUE THREAD

**Issue by timo-klarshift** [rmorrise/grails-cascade-validation#7]
If you for example call first validate() and later save() you have the child errors appearing twice in the parents Errors object ... 

Dont know if relevant for anyone, or if this plugin even still is maintained

**Comment by rmorrise** [comment]
@timo-klarshift Thanks for reporting this issue!

My company is actively using the plugin in numerous projects. Currently we don't have a pressing need to make plugin code changes. If you are able to fork and contribute to the plugin source, I can make time to review and test the changes, and publish a new plugin version.

**Comment by asoftwareguy** [comment]
@timo-klarshift can you provide a test case that exhibits this behavior?

**Comment by timo-klarshift** [comment]
I will provide a test case

**Comment by timo-klarshift** [comment]
Okay, I think its even different from what I thought first. What I am doing is not validating more than once, but just having a Parent -> Child structure, whereas Parent is a regular Domain and Child is a @Validatable in src/groovy which is transient in the Parent (in the real use case I transform the child to JSON and store it in the parent - but thats apart from the test) ...

I added an Integration Test. When I validate the Parent the error message from the child is addes twice to the parent. 

This is fixed for me already (had to modify the validator anyway), but I dont understand why its happening in the first place. 

Cant upload the zip file of the grails demo app, no other way at the moment to share: http://expirebox.com/download/1cbc8506326214b0517d3dec3551c4f1.html

let me know if expired already.

Thanks

**Comment by rmorrise** [comment]
If this is still a problem, please open an issue on the new GPC repository:
https://github.com/gpc/grails-cascade-validation/issues
